/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/chat/Avatar.vue')['default']
    AvatarBadge: typeof import('./src/components/profile/AvatarBadge.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    ChallengeModal: typeof import('./src/components/game/ChallengeModal.vue')['default']
    ChatConversationTopBar: typeof import('@/components/chatRooms/ChatConversationTopBar.vue')['default']
    ChatUserProfileSidebar: typeof import('@/components/chatRooms/ChatUserProfileSidebar.vue')['default']
    CoalitionFlag: typeof import('./src/components/profile/CoalitionFlag.vue')['default']
    ConversationsDrawer: typeof import('./src/components/chat/ConversationsDrawer.vue')['default']
    CreateDialog: typeof import('./src/components/chat/CreateDialog.vue')['default']
    DmContainer: typeof import('./src/components/chat/DmContainer.vue')['default']
    DoubleFactorModal: typeof import('./src/components/profile/DoubleFactorModal.vue')['default']
    FriendRequestBox: typeof import('./src/components/profile/FriendRequestBox.vue')['default']
    Friends: typeof import('./src/components/profile/Friends.vue')['default']
    GameStatusBadge: typeof import('./src/components/game/GameStatusBadge.vue')['default']
    Header: typeof import('./src/components/profile/Header.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    InviteDialog: typeof import('./src/components/chat/InviteDialog.vue')['default']
    JoinDialog: typeof import('./src/components/chat/JoinDialog.vue')['default']
    MembersDrawer: typeof import('./src/components/chat/MembersDrawer.vue')['default']
    MessageContact: typeof import('@/components/messages/MessageContact.vue')['default']
    MessagesContainer: typeof import('./src/components/chat/MessagesContainer.vue')['default']
    MessageTopBar: typeof import('@/components/messages/MessageTopBar.vue')['default']
    NavSearchBar: typeof import('./src/components/navbar/NavSearchBar.vue')['default']
    Notification: typeof import('./src/components/notifications/Notification.vue')['default']
    NotificationButton: typeof import('./src/components/navbar/NotificationButton.vue')['default']
    NotificationPopUp: typeof import('./src/components/notifications/NotificationPopUp.vue')['default']
    PasswordDialog: typeof import('./src/components/chat/PasswordDialog.vue')['default']
    PongGamePlayer: typeof import('./src/components/PongGamePlayer.vue')['default']
    ProfileCard: typeof import('./src/components/ProfileCard.vue')['default']
    ProfileDialog: typeof import('./src/components/chat/ProfileDialog.vue')['default']
    ProfileImage: typeof import('./src/components/ProfileImage.vue')['default']
    RoomContact: typeof import('@/components/chatRooms/RoomContact.vue')['default']
    RoomPasswordDialog: typeof import('./src/components/chat/roomPasswordDialog.vue')['default']
    RoomSelector: typeof import('./src/components/chat/RoomSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialLoginButton: typeof import('./src/components/SocialLoginButton.vue')['default']
    UserProfileButton: typeof import('./src/components/navbar/UserProfileButton.vue')['default']
    WaitingDialog: typeof import('./src/components/chat/WaitingDialog.vue')['default']
  }
}
