name: Frontend Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
#      - name: Type check
#        run: yarn type-check
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test:unit
      - name: Build
        run: yarn build

